api/urls.py
from django.urls import path
from .views import book_list, book_page, pdfUploadView
from . import routing

app_name = 'api'

urlpatterns = [
    path("book-list/", book_list),
    path('upload/', pdfUploadView.as_view()),
    path("book-page/<int:id>/", book_page, name="book-page"),
]

bookchat/urls.py
from django.urls import path, include
from .views import index, book_page, my_page, delete_chat_records, result_page, make_report
from . import routing

app_name = 'bookchat'

urlpatterns = [
    path("", index, name='index'),
    path("book-page/<int:id>/", book_page, name="book-page"),
    path("result-page/<int:id>/", result_page, name="result-page"),
    path("my-page/", my_page, name="my-page"),
    path("api/chat/<int:book_id>/delete/", delete_chat_records),
    path("api/chat/<int:book_id>/end/", make_report),
    # path("book-page/<id>/send_message/", send_message, name="send_message"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from bookchat.views import index
from django.conf import settings
from django.conf.urls.static import static
from account.views import register, login, user_profile

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("bookchat.urls")),
    path("common/", include("common.urls")),
    path("api/", include("api.urls")),
    path("", index, name="index"),  # 로그인 후 홈페이지로 redirect를 위함
    path("api/login/", login),
    path("api/register/", register),
    path('api/user-profile/', user_profile),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookchat/models.py
from django.db import models
from django.contrib.auth.models import User


class Book(models.Model):
    title = models.CharField(max_length=50, null=False) 
    book_cover = models.ImageField(upload_to='img')
    file = models.FileField(upload_to='pdf')
    intro = models.CharField(max_length=200, null=False)
    author = models.CharField(max_length=20, null=False)
    author_intro = models.CharField(max_length=200, null=False)
    pickle = models.FileField(upload_to='pickle', blank=True)
    # users = models.ManyToManyField(User, through='Chat', related_name='users')

    def __str__(self):
        return f"{self.title} ({self.author})"

class Chat(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    msg = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)  # 메시지 보낸 시간
    is_user_message = models.BooleanField(default=False)  # 사용자가 보낸 메시지 여부
    def __str__(self):
        return f'{self.timestamp}: {"User" if self.is_user_message else "Bot"} - {self.msg}'
    
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    debated_books = models.ManyToManyField(Book, blank=True, related_name='user')

bookchat/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.conf import settings
import os
import json
from django.urls import reverse

from .models import Book, UserProfile, Chat
from .generate_pkl import save_pickle
from .generate_model import ChainManager

# Create your views here.
def index(request):
    books = Book.objects.all() # DB의 모든 책 정보 불러오기
    path = settings.MEDIA_ROOT
    return render(request, 'bookchat/index.html', {
        "books": books,
        "path": path
    })

@login_required
def book_page(request, id):
    book = Book.objects.get(id = id) # 특정 id의 책 불러오기
    if not book.pickle:
        save_pickle(id) # pickle 파일이 없다면 만들어 주기
        # 로딩 화면 구축
    return render(request, 'bookchat/book_page.html', {
        "book": book
    })

def result_page(request, id):
    book = Book.objects.get(id = id) # 특정 id의 책 불러오기
    user = request.user
    return render(request, 'bookchat/result_page.html', {
        "book": book,
        "user": user
    })

def my_page(request):
    # user = None
    # if request.user.is_authenticated:
    #     user = request.user
    # user_profile = UserProfile.objects.get(user=user)
    # books = Book.objects.filter(user= user_profile)
    return render(request, 'bookchat/my_page.html', {})

@csrf_exempt
def send_message(request, id):
    if request.method == 'POST':
        # 챗봇 로직 처리 (답변 생성)
        user_message = request.POST.get('message', '')
        user = request.user

        chain_manager = ChainManager(id, user)

        # Use the chain to get the answer
        bot_reply = chain_manager.make_answer(user_message)

        return JsonResponse({'reply': bot_reply})
    else:
        return JsonResponse({'error': 'POST 요청만 지원합니다.'})

@csrf_exempt
def delete_chat_records(request, book_id):
    book = Book.objects.get(id=book_id)
    chat_records = Chat.objects.filter(user=request.user, book=book)
    chat_records.delete()
    return JsonResponse({"success": True})

@csrf_exempt
def make_report(request, book_id):
    id = book_id
    redirect_url = None
    if request.method == 'POST':
        chat_history = json.loads(request.body)['chatHistory']
        print(chat_history)
        # 리디렉션할 URL을 지정합니다. 예를 들어, 'report' 뷰로 리디렉션할 수 있습니다.
        redirect_url = reverse('bookchat:result-page', args=[id])
        print(redirect_url)
    return HttpResponseRedirect(redirect_url)
        

bookchat/templates/bookchat/book_page.html
{% extends 'base.html' %}
{% load static %}
{% load sass_tags %}

{% block head %}
<link href="{% sass_src 'bookchat/css/book_page.scss' %}?v1" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}

<div class="chat-container">
    <div class="chat-room-name">{{ book.title }}</div>
    <div class="chat-messages" id="chatMessages">
      <!-- 메시지가 표시될 영역 -->
    </div>
    <div class="user-input">
      <button id="reset"><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 30 30" fill="none">
        <path d="M7.5 16.6062C7.5 14.5437 8.3375 12.6687 9.7 11.3062L7.925 9.5312C6.125 11.3437 5 13.8437 5 16.6062C5 21.7062 8.8125 25.9062 13.75 26.5187V23.9937C10.2125 23.3937 7.5 20.3187 7.5 16.6062ZM25 16.6062C25 11.0812 20.525 6.6062 15 6.6062C14.925 6.6062 14.85 6.6187 14.775 6.6187L16.1375 5.2562L14.375 3.4812L10 7.8562L14.375 12.2312L16.1375 10.4687L14.7875 9.1187C14.8625 9.1187 14.9375 9.1062 15 9.1062C19.1375 9.1062 22.5 12.4687 22.5 16.6062C22.5 20.3187 19.7875 23.3937 16.25 23.9937V26.5187C21.1875 25.9062 25 21.7062 25 16.6062Z" fill="#376042"/>
      </svg></button>
      <div class="userMessage-box">
        <input type="text" id="userMessage">
        <button type="button" id="submit"><img src="{% static 'img/submit.svg' %}" class="img-fluid" alt="..."></button>
      </div>

    </div>
  </div>
  <!-- <button id="end">토론 끝내기</button> -->
  
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.0/axios.min.js"></script>
  <script type="module" src="{% static 'bookchat/js/script.js' %}"></script>
  <script type="module" src="{% static 'bookchat/js/book_page.js' %}"></script>

{% endblock %}

bookchat/templates/bookchat/index.html
{% extends 'base.html' %}
{% load static %}

{% load sass_tags %}

{% block head %}
<link href="{% sass_src 'bookchat/css/index.scss' %}?v9" rel="stylesheet" type="text/css" />

{% endblock %}

{% block content %}

<!-- <div class="book-list">
<h2>추천도서 목록</h2>
<ul>
    {% for book in books %}
    <li><a href="{% url 'bookchat:book-page' book.id %}">{{ book.title }}</a></li>
    {% endfor %}
</ul>
</div> -->

<section class="body1 container-fluid">

    <div class="thumbnail">
        <div class="thumbnail-texts">
            <div class="thumbnail-titles">
                <div class="thumbnail-title">소통하는 책</div>
                <div class="thumbnail-subtitle">새로운 독서토론</div>
            </div>
            <div class="thumbnail-explain">
                <p>언제 어디서든 당신의 독서 토론 파트너</p>
                <p>원하는 시간 장소에서 인공지능 챗봇과 독서토론을 해보세요.</p>
            </div>
        </div>
        <img src="{% static 'bookchat/img/landing_img.svg' %}" class="img-fluid landing-img" alt="...">
    </div>
</section>

<div class="body2">
    <div class="book-sector">
    <div class="menus">
        <div class="menu_buttons">
            <button class="menu_button active"><span class="menu_contents active">전체보기</span></button>
            <button class="menu_button"><span class="menu_contents">BEST</span></button>
            <button class="menu_button"><span class="menu_contents">고전</span></button>
        </div>

    </div>
    <div class="books">
        {% for book in books %}
        <div class="book-info">
            <a href="{% url 'bookchat:book-page' book.id %}"><img src="{{ book.book_cover.url }}"></a>
            <span class="book-title">{{book.title}}</span>
            <span class="book-author">{{book.author}}</span>
        </div>
        {% endfor %}
    </div>

</div>
</div>
</section>
<section class="footer">
    <img src="{% static 'bookchat/img/footer.svg' %}" class="footer-img" alt="...">
</section>

{% endblock %}

bookchat/templates/bookchat/my_page.html
{% extends 'base.html' %}
{% load static %}
{% load sass_tags %}

{% block content %}

<!-- <h1>{{username}}님의 페이지</h1>
<h2>현재 토론 중인 책 목록</h2>
{% for book in books %}
<div>
    {{book}}
</div>
{% endfor %}
<h2>토론 완료 책 목록</h2>
{% for book in books %}
<div>
    {{book}}
</div>
{% endfor %} -->
마이페이지 구현 예정

{% endblock %}

bookchat/templates/bookchat/result_page.html
{% extends 'base.html' %}
{% load static %}
{% load sass_tags %}

{% block head %}
<link href="{% sass_src 'bookchat/css/result_page.scss' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}

토론 결과 구현 예정

{% endblock %}