api/urls.py
from django.urls import path
from .views import book_list, book_page, pdfUploadView
from . import routing

app_name = 'api'

urlpatterns = [
    path("book-list/", book_list),
    path('upload/', pdfUploadView.as_view()),
    path("book-page/<int:id>/", book_page, name="book-page"),
]

bookchat/urls.py
from django.urls import path, include
from .views import index, book_page, my_page, delete_chat_records, result_page, make_report
from . import routing

app_name = 'bookchat'

urlpatterns = [
    path("", index, name='index'),
    path("book-page/<int:id>/", book_page, name="book-page"),
    path("result-page/<int:id>/", result_page, name="result-page"),
    path("my-page/", my_page, name="my-page"),
    path("api/chat/<int:book_id>/delete/", delete_chat_records),
    path("api/chat/<int:book_id>/end/", make_report),
    # path("book-page/<id>/send_message/", send_message, name="send_message"),
]

common/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(template_name='common/login.html'), name='login'), # 장고 기본제공 로그인 창 활용
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'), 
    path('auto-login/', views.auto_login, name='auto-login'), 
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from bookchat.views import index
from django.conf import settings
from django.conf.urls.static import static
from account.views import register, login, user_profile

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("bookchat.urls")),
    path("common/", include("common.urls")),
    path("api/", include("api.urls")),
    path("", index, name="index"),  # 로그인 후 홈페이지로 redirect를 위함
    path("api/login/", login),
    path("api/register/", register),
    path('api/user-profile/', user_profile),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
{% load sass_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BookChatting - 책과의 채팅</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <!-- bookchat CSS -->
    <link href="{% sass_src 'css/common.scss' %}" rel="stylesheet" type="text/css" />
    <link href="{% sass_src 'css/navbar.scss' %}?v8" rel="stylesheet" type="text/css" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@700&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Lato:wght@700&display=swap" rel="stylesheet">
    {% block head %}
    {% endblock %}
</head>
<body>
    {% include 'navbar.html' %}
    
    {% block content %}
    {% endblock %}
    <script src="{% static 'bootstrap\dist\js\bootstrap.min.js' %}"></script>

</body>
</html>

templates/navbar.html
<!-- <nav class="navbar navbar-expand-lg bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'bookchat:index' %}">BookChatting</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
  </nav> -->
  {% load static %}

  <nav class="navbar navbar-expand-lg border-bottom">
      <div class="navbar-left">
      <a class="navbar-brand" href="{% url 'bookchat:index' %}"><img src="{% static 'img/logo.svg' %}" class="img-fluid logo-icon" alt="..."><span class="logo_name">SocraChat</span></a>
      </div>
      <div class="navbar-right">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="#navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            {% if user.is_authenticated %}
            <div class="nav-link signup" href="{% url 'bookchat:my-page' %}">마이페이지({{ user.username }})</div>
            {% endif %}
        </li>
        <li>
          {% if not user.is_authenticated %}
          <a class="nav-link signup" href="{% url 'common:signup' %}">회원가입</a>
          {% endif %}
      </li>
        <li class="nav-item">
          {% if user.is_authenticated %}
          <a class="nav-link login" href="{% url 'common:logout' %}"><svg class="login-icon" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18" fill="none">
            <path d="M9 1.5C4.86 1.5 1.5 4.86 1.5 9C1.5 13.14 4.86 16.5 9 16.5C13.14 16.5 16.5 13.14 16.5 9C16.5 4.86 13.14 1.5 9 1.5ZM5.5125 13.875C6.495 13.17 7.695 12.75 9 12.75C10.305 12.75 11.505 13.17 12.4875 13.875C11.505 14.58 10.305 15 9 15C7.695 15 6.495 14.58 5.5125 13.875ZM13.605 12.84C12.3375 11.85 10.74 11.25 9 11.25C7.26 11.25 5.6625 11.85 4.395 12.84C3.525 11.7975 3 10.4625 3 9C3 5.685 5.685 3 9 3C12.315 3 15 5.685 15 9C15 10.4625 14.475 11.7975 13.605 12.84Z" fill="white"/>
            <path d="M9 4.5C7.5525 4.5 6.375 5.6775 6.375 7.125C6.375 8.5725 7.5525 9.75 9 9.75C10.4475 9.75 11.625 8.5725 11.625 7.125C11.625 5.6775 10.4475 4.5 9 4.5ZM9 8.25C8.3775 8.25 7.875 7.7475 7.875 7.125C7.875 6.5025 8.3775 6 9 6C9.6225 6 10.125 6.5025 10.125 7.125C10.125 7.7475 9.6225 8.25 9 8.25Z" fill="white"/><span class="login-text">로그아웃</span></a>
          {% else %}
          <a class="nav-link login" href="{% url 'common:login' %}"><svg class="login-icon" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18" fill="none">
            <path d="M9 1.5C4.86 1.5 1.5 4.86 1.5 9C1.5 13.14 4.86 16.5 9 16.5C13.14 16.5 16.5 13.14 16.5 9C16.5 4.86 13.14 1.5 9 1.5ZM5.5125 13.875C6.495 13.17 7.695 12.75 9 12.75C10.305 12.75 11.505 13.17 12.4875 13.875C11.505 14.58 10.305 15 9 15C7.695 15 6.495 14.58 5.5125 13.875ZM13.605 12.84C12.3375 11.85 10.74 11.25 9 11.25C7.26 11.25 5.6625 11.85 4.395 12.84C3.525 11.7975 3 10.4625 3 9C3 5.685 5.685 3 9 3C12.315 3 15 5.685 15 9C15 10.4625 14.475 11.7975 13.605 12.84Z" fill="white"/>
            <path d="M9 4.5C7.5525 4.5 6.375 5.6775 6.375 7.125C6.375 8.5725 7.5525 9.75 9 9.75C10.4475 9.75 11.625 8.5725 11.625 7.125C11.625 5.6775 10.4475 4.5 9 4.5ZM9 8.25C8.3775 8.25 7.875 7.7475 7.875 7.125C7.875 6.5025 8.3775 6 9 6C9.6225 6 10.125 6.5025 10.125 7.125C10.125 7.7475 9.6225 8.25 9 8.25Z" fill="white"/>
          </svg><span class="login-text">로그인</span></a>
          {% endif %}
      </li>

    </ul>
      </div>
      </div>
  </nav>